name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: withastro/action@v0
        with:
          path: .
          site: https://austinlay23.github.io/freelance-automator-site/
          build-dir: dist
